### ISSUE TITLE
Compiling error with lib_sass

### ISSUE THREAD

**Issue by keesse** [TheEEs/markdown#1]
Hi,
I saw your post on the crystal forum in *State & Plans of GUI development with Crystal*.
On the alizarin github page I saw the link to Markdown.
While compiling on Ubuntu 20.10 with Crystal 1.0.0 and 0.36.1 I get the following error:
```
$ crystal ./src/markdown.cr 
Showing last frame. Use --error-trace for full trace.

In lib/sass/src/lib_sass.cr:126:80

 126 | fun option_get_input_path = sass_option_get_input_path(opt : SassOptions*) : Char*?
                                                                                    ^
Error: only primitive types, pointers, structs, unions, enums and tuples are allowed in lib declarations, not (Pointer(UInt8) | Nil)
```
Any ideas what to do?

Kind regards,

Kees Serier

**Comment by BlobCodes** [comment]
@keesse 

Here's a quick fix:
- Remove `require "sass"` from src/markdown.cr
- create a file `res/app.css` with the following contents:
    ```css
    body div.CodeMirror {
        height: 85vh;
    }
    
    body #init-textarea{
        display: none;
    }
    ```
- In `res/index.html.ecr`, replace the line `<%= Sass.compile_file("#{__DIR__}/app.scss") %>` (l.25) with: `<%= File.read("#{__DIR__}/app.css") %>`
- In `src/editor.cr`, replace `return` (line 18) with `next`
- In `shards.yml`, replace the alizarin dependency with my fork (github: BlobCodes/alizarin)
- Remove lib folder, run shards and compile

**Comment by TheEEs** [comment]
@keesse updating shard **sass.cr** to the lastest version will solve the problem.
`
$ shards update
`

**Comment by keesse** [comment]
@BlobCodes, @TheEEs  thank you very much for replying.
Using the updated sass.cr, I still had problems installing it, today I had more time to look at it and got it installed.
And I finally could build `markdown`, it looks good, I will have a closer look at both Alizarin and markdown!
